### ISSUE TITLE
Cannot build from source: msgpack/sysdep.hpp:102:10: fatal error: boost/predef/other/endian.h: No such file or directory

### ISSUE THREAD

**Issue by kevinsmia1939** [OpenChemistry/avogadrolibs#1188]
I want to update msgpack for Avogadro2 for Flatpak.
But stuck as error shown below. I think it likely msgpack error rather than Avogadro.

**Avogadro version: (please complete the following information from the About box):**
 - Avogadrolibs: 1.97.0
 - Qt: 
```
Running: qmake --version
QMake version 3.1
Using Qt version 5.15.6 in /usr/lib/x86_64-linux-gnu
```

**Desktop version: (please complete the following information):**
 - OS:
```
 Operating System: openSUSE Tumbleweed 20221015
KDE Plasma Version: 5.26.0
KDE Frameworks Version: 5.99.0
Qt Version: 5.15.6
Kernel Version: 6.0.1-1-default (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 4600H with Radeon Graphics
Memory: 7.6 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1650 Ti/PCIe/SSE2
Manufacturer: LENOVO
Product Name: 82B5
System Version: Lenovo Legion 5 15ARH05
```
 - Compiler
```
flatpak --version
Flatpak 1.14.0
flatpak-builder --version
flatpak-builder 1.2.2

 Running: cmake --version
cmake version 3.23.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
Running: gcc --version
gcc (GCC) 11.3.0
```

**Describe the bug**
```
[ 20%] Building CXX object avogadro/io/CMakeFiles/AvogadroIO.dir/lammpsformat.cpp.o
[ 20%] Building CXX object avogadro/io/CMakeFiles/AvogadroIO.dir/hdf5dataformat.cpp.o
[ 20%] Building CXX object avogadro/io/CMakeFiles/AvogadroIO.dir/mmtfformat.cpp.o
In file included from /app/include/msgpack/v1/pack_decl.hpp:15,
                 from /app/include/msgpack/pack_decl.hpp:13,
                 from /app/include/msgpack/pack.hpp:13,
                 from /app/include/msgpack/v1/object_decl.hpp:14,
                 from /app/include/msgpack/object_decl.hpp:14,
                 from /app/include/msgpack/object.hpp:13,
                 from /app/include/msgpack.hpp:10,
                 from /app/include/mmtf/structure_data.hpp:25,
                 from /app/include/mmtf/decoder.hpp:16,
                 from /app/include/mmtf.hpp:15,
                 from /run/build/avogadrolibs/avogadrolibs/avogadro/io/mmtfformat.cpp:17:
/app/include/msgpack/sysdep.hpp:102:10: fatal error: boost/predef/other/endian.h: No such file or directory
  102 | #include <boost/predef/other/endian.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [avogadro/io/CMakeFiles/AvogadroIO.dir/build.make:272: avogadro/io/CMakeFiles/AvogadroIO.dir/mmtfformat.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```
Snippet from the Flatpak manifest.

```
  - name: Boost
    buildsystem: simple
    build-commands:
      - ./bootstrap.sh --prefix=/app
      - ./b2 install --build-type=complete link=shared --layout=versioned runtime-link=shared
        cxxflags="$CXXFLAGS" linkflags="$LDFLAGS" -j $FLATPAK_BUILDER_N_JOBS
    sources:
      - type: archive
        url: https://boostorg.jfrog.io/artifactory/main/release/1.80.0/source/boost_1_80_0.tar.bz2
        sha256: 1e19565d82e43bc59209a168f5ac899d3ba471d55c7610c677d4ccf2c9c500c0
        x-checker-data:
          type: anitya
          project-id: 6845
          stable-only: true
          url-template: https://boostorg.jfrog.io/artifactory/main/release/$version/source/boost_${major}_${minor}_${patch}.tar.bz2

  - name: msgpack
    buildsystem: cmake
    config-opts:
      - -DBUILD_SHARED_LIBS:BOOL=ON
      # - -DMSGPACK_ENABLE_STATIC:BOOL=OFF
      # - -DCMAKE_INSTALL_LIBDIR:PATH=lib
      - -DMSGPACK_BUILD_EXAMPLES:BOOL=OFF
      - -DMSGPACK_BUILD_DOCS:BOOL=OFF
      - -DMSGPACK_CXX20:BOOL=ON
      - -DMSGPACK_BUILD_TESTS:BOOL=ON
    post-install:
      - make test
    sources:
      - type: archive
        url: https://github.com/msgpack/msgpack-c/releases/download/cpp-4.1.2/msgpack-cxx-4.1.2.tar.gz
        sha256: eeddd7faeacbc12e10052bd1e3ec78bd26c69bfbbea9f9264c7ffce9b1ede7b1
        x-checker-data:
          type: anitya
          project-id: 12278
          stable-only: true
          url-template: https://github.com/msgpack/msgpack-c/releases/download/cpp-$version/msgpack-cxx-$version.tar.gz

  - name: avogadrolibs
    buildsystem: cmake
    builddir: true
    subdir: avogadrolibs
    config-opts:
      - -DOpenGL_GL_PREFERENCE=GLVND
      - -DUSE_SYSTEM_GENXRDPATTERN:BOOL=ON
      - -DCMAKE_BUILD_TYPE:STRING=Release
      - -DENABLE_TRANSLATIONS:BOOL=ON
      - -DUSE_HDF5:BOOL=ON
      - -DUSE_PYTHON:BOOL=ON
      - -DUSE_QT:BOOL=ON
      - -DUSE_LIBMSYM:BOOL=ON
      - -DUSE_SPGLIB:BOOL=ON
      - -DUSE_MMTF:BOOL=ON
      - -DUSE_MOLEQUEUE:BOOL=ON
      - -DUSE_PROTOCALL:BOOL=OFF
      - -DUSE_VTK:BOOL=OFF
      - -DBUILD_GPL_PLUGINS:BOOL=ON
      - -DBUILD_STATIC_PLUGINS:BOOL=ON
      - -Dlibmsym_DIR:PATH=${FLATPAK_DEST}/lib/cmake/libmsym
      - -Dpybind11_DIR:PATH=${FLATPAK_DEST}/lib/python3.9/site-packages/pybind11-2.6.2-py3.9.egg/pybind11/share/cmake/pybind11/
    sources:
      - type: git
        url: https://github.com/OpenChemistry/avogadrolibs
        tag: 1.97.0
        commit: 82938e4f5ce188a1e53300d263167bebe717f5b2
        dest: avogadrolibs
        x-checker-data:
          type: git
          tag-pattern: ^([\d.]+)$
      - type: archive
        url: https://github.com/OpenChemistry/molecules/archive/refs/heads/master.zip
        sha256: a1275e8139c2021127514abdccfb13e20b1cca0791d14459e9f50065ca566f02
        dest: molecules
        dest-filename: molecules.zip
      - type: archive
        url: https://github.com/OpenChemistry/crystals/archive/refs/heads/master.zip
        sha256: 0365aa346ccc9f77a849cd10964ebcace96621f847216546e49c386f071119e7
        dest: crystals
        dest-filename: crystals.zip
```
Full Flatpak manifest
https://github.com/kevinsmia1939/org.openchemistry.Avogadro2
