### ISSUE TITLE
does not build against VTK-9

### ISSUE THREAD

**Issue by drew-parsons** [OpenChemistry/avogadrolibs#516]
**Avogadro version: **
 - Avogadrolibs: 1.93.0+git20201104.926573b-1
 - Qt: 5.15.2+dfsg-2
 - VTK: 9.0.1+dfsg1-8

**Desktop version: (please complete the following information):**
 - OS: Linux 5.10.9-1
 - Version Debian unstable
 - Compiler gcc 10.2.1

**Describe the bug**

VTK-9 has made major changes to the way client applications build against it.  Some description is provided at 
https://vtk.org/doc/nightly/html/md__home_kitware_dashboards_buildbot_vtk_nightly-master-ike-linux-shared-release_doc_nightly_osm749dd663df9981384f2598c108aac3b0.html
and
https://vtk.org/doc/nightly/html/md__home_kitware_dashboards_buildbot_vtk_nightly-master-ike-linux-shared-release_doc_nightly_osm5be4e3c8a508a13e731d7b85aeec815a.html

The main practical challenge for avogadrolibs (i.e. the thing I haven't been able to figure out myself), is that `VTK_INCLUDE_DIRS` no longer exists, which is being used in avogadro/vtk/CMakeLists.txt. So avogadrolibs simply does not build: the generated make scripts do not know to look in /usr/include/vtk-9.0 to find QVTKOpenGLStereoWidget.h, for instance (QVTKOpenGLStereoWidget.h is the VTK-9 replacement for QVTKOpenGLWidget.h)
```
Scanning dependencies of target AvogadroVtk
make  -f avogadro/vtk/CMakeFiles/AvogadroVtk.dir/build.make avogadro/vtk/CMakeFiles/AvogadroVtk.dir/build
make[3]: Entering directory '/projects/avogadrolibs/build'
[ 33%] Building CXX object avogadro/vtk/CMakeFiles/AvogadroVtk.dir/AvogadroVtk_autogen/mocs_compilation.cpp.o
cd /projects/avogadrolibs/buildavogadro/vtk && /usr/bin/c++ -DAvogadroVtk_EXPORTS -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB  -I/projects/avogadrolibs/build/avogadro/vtk -isystem /usr/include/eigen3 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++  -fPIC -std=c++17 -o CMakeFiles/AvogadroVtk.dir/AvogadroVtk_autogen/mocs_compilation.cpp.o -c /projects/avogadrolibs/build/avogadro/vtk/AvogadroVtk_autogen/mocs_compilation.cpp
In file included from /projects/avogadrolibs/build/avogadro/vtk/AvogadroVtk_autogen/EWIEGA46WW/moc_vtkglwidget.cpp:10,
                 from /projects/avogadrolibs/build/avogadro/vtk/AvogadroVtk_autogen/mocs_compilation.cpp:2:

../../../../../avogadro/vtk/vtkglwidget.h:22:10: fatal error: QVTKOpenGLWidget.h: No such file or directory
   22 | #include <QVTKOpenGLWidget.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

The new way to handle VTK in CMakeLists.txt is desribed in "Module Migration". Apparently `vtk_module_autoinit()` needs to be used. But my attempts to add it show that it's not enough to simply add
```
vtk_module_autoinit(
  TARGETS AvogadroVtk
 # MODULES ${VTK_LIBRARIES} # "works", but is not recommended.
 MODULES    VTK::RenderingOpenGL2 VTK::GUISupportQt VTK::DomainsChemistry
   VTK::RenderingVolumeOpenGL2 VTK::ViewsCore VTK::RenderingFreeType
   VTK::ChartsCore VTK::ViewsContext2D VTK::RenderingContextOpenGL2
)
```
to avogadro/vtk/CMakeLists.txt. 

The CylinderExample at https://kitware.github.io/vtk-examples/site/Cxx/GeometricObjects/CylinderExample/ does work. I think the difference is that the example uses `add_executable` while avogadro/vtk uses `avogadro_add_library` (rather than `add_library`), though I'm not sure.

 Perhaps `avogadro_add_library` needs to be updated to be able to work with `vtk_module_autoinit()`.

 Judging by the example, what `vtk_module_autoinit()` will do is place `CXX_INCLUDES = -isystem /usr/include/vtk-9.0` into `build/avogadro/vtk/CMakeFiles/AvogadroVtk.dir/flags.make` )

**Comment by ghutchis** [comment]
I definitely need to defer to @cryos here - certainly it would be nice to update to VTK9.

**Comment by ghutchis** [comment]
Ping @cryos - do you have a bit of time to look at this soon? I'd like to address this before we release 1.94.

**Comment by ghutchis** [comment]
@drew-parsons - there's now a Flatpak and it looks like @kevinsmia1939 was able to work around this:

https://github.com/flathub/org.openchemistry.Avogadro2/blob/master/org.openchemistry.Avogadro2.yaml
```
  - name: VTK
    buildsystem: cmake
    builddir: true
    config-opts:
    - -DBUILD_SHARED_LIBS=ON
    - -DOpenGL_GL_PREFERENCE=GLVND
    - -DBUILD_TESTING:BOOL=OFF
    - -DVTK_Group_Rendering:BOOL=OFF
    - -DVTK_Group_StandAlone:BOOL=OFF
    - -DModule_vtkDomainsChemistry:BOOL=ON
    - -DModule_vtkViewsContext2D:BOOL=ON
    - -DModule_vtkChartsCore:BOOL=ON
    - -DModule_vtkRenderingVolumeOpenGL2:BOOL=ON
    - -DModule_vtkGUISupportQt:BOOL=ON
    - -DModule_vtkRenderingQt:BOOL=ON
    - -DModule_vtkViewsInfovis:BOOL=OFF
    - -DModule_vtkRenderingFreeTypeOpenGL2:BOOL=ON
    - -DVTK_USE_SYSTEM_ZLIB:BOOL=ON
    - -DVTK_USE_SYSTEM_EIGEN:BOOL=ON
    - -DVTK_BUILD_QT_DESIGNER_PLUGIN:BOOL=OFF
    - -DVTK_QT_VERSION:STRING=5
    - -DCMAKE_BUILD_TYPE=Release
    - -DVTK_PYTHON_VERSION:STRING=3
    - -DVTK_GROUP_ENABLE_Qt=YES
    - -DVTK_MODULE_ENABLE_VTK_GUISupportQt=YES
    - -DModule_vtkGUISupportQtOpenGL:BOOL=ON
    - -DVTK_BUILD_COMPILE_TOOLS_ONLY:BOOL=ON
```
